stages:
  - test
  - doc

variables:
  DEBIAN_FRONTEND: "noninteractive"

test:
  image: gcc:latest
  stage: test
  script:
    - apt-get update -y
    - apt-get install cmake -y
    - mkdir build
    - cd build
    - cmake ..
    - make -j4

doc:
  image: ubuntu:latest
  stage: doc
  script:
    - apt-get update -y
    - apt-get install python3-sphinx python3-pip make -y
    - pip3 install sphinxcontrib-mermaid
    - sphinx-build -b html . ./_build
    - mv _build/ public/
  artifacts:
    paths:
      - public
  only:
    - master
